version: "3.7"

services:
  server:
    image: web-app:1.0
    container_name: application
    depends_on:
      - database
    ports: 
      - '5000:5000'
    networks:
      - con-db
    tty: true

  database:
    image: 'postgres:14.5-alpine'
    container_name: database
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      - con-db
    restart: always
    tty: true

networks:
  con-db:
    driver: bridge