version: "3.7"

services:
  server:
    build: .
    container_name: application
    depends_on:
      - database
    ports: 
      - '5000:5000'
    networks:
      - con-db

  database:
    image: 'postgres:14.5-alpine'
    container_name: database
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './database/postgres/docker-entrypoint-initdb/extension.sql:/docker-entrypoint-initdb.d/init.sql'
      # - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - '5432'
    networks:
      - con-db
    restart: always

networks:
  con-db:
    driver: bridge
